apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-chart.fullname" . }}
  namespace: {{ .Values.db.namespace }}
type: Opaque    
data:
  {{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end}}