apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb-chart.fullname" . }}
  namespace: {{ .Values.db.namespace }}
  labels:
    {{- include "mongodb-chart.labels" . | nindent 4 }}
    {{- toYaml .Values.service.extraLabels | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http    
      {{- if eq .Values.service.type "NodePort"}}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "mongodb-chart.selectorLabels" . | nindent 4 }}
    {{- toYaml .Values.pod.extraLabels | nindent 4 }}    
