# Default values for mongodb-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

db:
  namespace: test

image:
  repository: mongo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "4.0.8"

volumeMount: 
  name: "mongodb-secret"
  path: "/etc/mongodb-secret"
  readOnly: true 

volume:
  items:
    - key: "MONGO_ROOT_USERNAME"
      path: "admin/MONGO_ROOT_USERNAME"
      mode: 0444
    - key: "MONGO_ROOT_PASSWORD"
      path: "admin/MONGO_ROOT_PASSWORD"
      mode: 0444



secret:
  data:
    MONGO_ROOT_USERNAME: admin
    MONGO_ROOT_PASSWORD: password

env:
  mongo:
    secret:
    - name: MONGO_INITDB_ROOT_USERNAME_FILE
      value: /etc/mongodb-secret/admin/MONGO_ROOT_USERNAME
    - name: MONGO_INITDB_ROOT_PASSWORD_FILE
      value: /etc/mongodb-secret/admin/MONGO_ROOT_PASSWORD


imagePullSecrets: []
nameOverride: "mongodb"
fullnameOverride: "mongodb"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  name: mongo-mongodb
  type: ClusterIP
  port: 27017
  nodePort: 30994
  extraLabels:
    name: mongo-mongodb
    app: database

pod:
  extraLabels:
    name: mongodb-standalone
    app: database   

deploy:
  extraLabels:
    app: mongodb-standalone

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
      - path: /
        backend:
          serviceName: chart-example.local
          servicePort: 80
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
